version: 1.0.{build}

branches:
  # whitelist
  only:
    - master
artifacts:

  # pushing a single file with environment variable in path and "Deployment name" specified
  - path: FlickrView\bin\debug\FlickrView.exe
    name: FlickrView
    
before_build:
  - nuget restore
  
 