version: 1.0.{build}

artifacts:

  # pushing a single file with environment variable in path and "Deployment name" specified
  - path: FlickrView\bin\debug\FlickrView.exe
    name: FlickrView
    
before_build:
  - nuget restore

deploy:
  description: 'FlickrView - WPF Application'
  tag: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: GCYjUnTt08CJQqjbdzBQqoh+FY3N6/zyoYR5cY7FjERdRYrxRT3dmTefgoQ3mMd6 # your encrypted token from GitHub
  artifact: FlickrView            # upload all NuGet packages to release assets
  on:               # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only

 