version: 1.0.{build}

artifacts:

  # pushing a single file with environment variable in path and "Deployment name" specified
  - path: Binaries\FlickrView.exe
    name: FlickrView
    
before_build:
  - nuget restore

deploy:
  description: 'FlickrView - WPF Application'
  provider: GitHub
  artifact: FlickrView           
  draft: false
  prerelease: false
  on:
    branch: master                
    APPVEYOR_REPO_TAG: true       
 