version: 1.0.{build}

artifacts:

  # pushing a single file with environment variable in path and "Deployment name" specified
  - path: Binaries\FlickrView.exe
    name: FlickrView
    
before_build:
  - nuget restore

deploy:
  - provider: S3
    access_key_id:
      secure: xqzZX7EAHPbOBzxzoGZiwMOBfn8kmeM+CPfg9fchgQc=
    secret_access_key:
      secure: oCvOViNHeHV4+54zVp768H2N/PdghtrM/CBjOCuj0XOgQsVXgoAxy/SMeliTwLuM
    bucket: flickrview
    folder: flickrview
    region: ap-south-1
    artifact: FlickrView
    set_public: true
   
 
